v1.0.0: Release the chart (#2) [release-type helm]

diff --git a/.github/workflows/helm.yaml b/.github/workflows/helm.yaml
--- a/.github/workflows/helm.yaml
+++ b/.github/workflows/helm.yaml
@@ -1,4 +1,4 @@
-name: Build & Test Helm
+name: Build, Test & Release Helm Chart
 on:
   push:
     branches:
@@ -13,13 +13,14 @@ jobs:
       - uses: d3adb5/helm-unittest-action@v2
         with:
           unittest-version: v0.4.2
+          charts: charts/swagger-ui-git-sync
 
       - run: helm lint . -f tests/test-values.yaml
+        working-directory: charts/swagger-ui-git-sync
   
   update-readme:
     runs-on: ubuntu-latest
     needs: ["test"]
-    if: ${{ github.ref != 'refs/heads/main' }}
     steps:
       - name: Install readme-generator
         run: |
@@ -34,11 +35,71 @@ jobs:
       - uses: actions/checkout@v4
 
       - name: Update README
-        run: /tmp/readmegen/readmegen -v values.yaml -r README.md
+        run: /tmp/readmegen/readmegen -v charts/swagger-ui-git-sync/values.yaml -r README.md
 
       - name: Commit README
         uses: EndBug/add-and-commit@v9
         with:
           add: README.md
           message: Updating README.md [skip ci]
+          push: true
+
+  release-chart:
+    runs-on: ubuntu-latest
+    needs: ["test", "update-readme"]
+    if: ${{ contains(github.event.commits[0].message, '[release-type helm]') }}
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          fetch-depth: 0  # chart-releaser needs a full history
+      - name: Configure Git
+        run: |
+          git config user.name "$GITHUB_ACTOR"
+          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
+      - name: Install Helm
+        uses: azure/setup-helm@v4
+        env:
+          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
+
+      - name: Get chart version
+        id: chart-details
+        run: |
+          cat Chart.yaml | yq -r ".version" | awk '{printf "version=%s", $0 }' - >> $GITHUB_OUTPUT
+        working-directory: charts/swagger-ui-git-sync
+      - name: Version enforcer
+        run: |
+          if ${{ (!contains(steps.chart-details.outputs.version, '-')) && (github.ref != 'refs/heads/main') }}; then
+            echo "Error: attempting to release a final version from a non-main branch!"
+            exit 1
+          fi
+
+      - name: Release chart and update public index
+        uses: helm/chart-releaser-action@v1
+        with:
+          charts_dir: "charts"
+          # If SNAPSHOT, overwrite release. Else, skip release if it already exists
+          skip_existing: ${{ ! contains(steps.chart-details.outputs.version, '-SNAPSHOT') }}
+          pages_branch: gh-pages
+          config: helm-releaser-config.yaml
+        env:
+          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  # For now the only thing we're serving publicly is the README
+  update-gh-pages:
+    runs-on: ubuntu-latest
+    needs: ["release-chart"]
+    if: ${{ contains(github.event.commits[0].message, '[release-type helm]') && github.ref == 'refs/heads/main' }}
+    steps:
+      - uses: actions/checkout@v4
+      - name: Store README
+        run: cp README.md /tmp/
+      - uses: actions/checkout@v4
+        with:
+          ref: gh-pages
+      - run: mv /tmp/README.md ./
+      - name: Commit README
+        uses: EndBug/add-and-commit@v9
+        with:
+          add: README.md
+          message: Updating README.md
           push: true
