try release a snapshot

diff --git a/.github/workflows/helm.yaml b/.github/workflows/helm.yaml
--- a/.github/workflows/helm.yaml
+++ b/.github/workflows/helm.yaml
@@ -4,17 +4,9 @@ on:
     branches:
       - "**"
 
-# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
-# permissions:
-#   contents: read
-#   pages: write
-#   id-token: write
-
 jobs:
   test:
     runs-on: ubuntu-latest
-    # TODO
-    if: ${{ false }}
     steps:
       - uses: actions/checkout@v4
 
@@ -29,9 +21,6 @@ jobs:
   update-readme:
     runs-on: ubuntu-latest
     needs: ["test"]
-    # TODO
-    if: ${{ false }}
-    # if: ${{ github.ref != 'refs/heads/main' }}
     steps:
       - name: Install readme-generator
         run: |
@@ -57,9 +46,8 @@ jobs:
 
   release-chart:
     runs-on: ubuntu-latest
-    # TODO needs: ["test"]
-    # TODO if: ${{ github.ref == 'refs/heads/main' }}
-    # TODO [release-type helm]
+    needs: ["test", "update-readme"]
+    if: ${{ contains(github.event.commits[0].message, '[release-type helm]') }}
     steps:
       - uses: actions/checkout@v4
         with:
@@ -73,11 +61,24 @@ jobs:
         env:
           GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
 
+      - name: Get chart version
+        id: chart-details
+        run: |
+          cat Chart.yaml | yq -r ".version" | awk '{printf "version=%s", $0 }' - >> $GITHUB_OUTPUT
+        working-directory: charts/swagger-ui-git-sync
+      - name: Version enforcer
+        run: |
+          if [ ${{ !contains(steps.chart-details.version, '-') && github.ref != 'refs/heads/main'}} ]; then
+            echo "Error: attempting to release a final version from a non-main branch!"
+            exit 1
+          fi
+
       - name: Release chart
         uses: helm/chart-releaser-action@v1
         with:
           charts_dir: "charts"
-          skip_existing: true  # TODO false for SNAPSHOTS
+          # If SNAPSHOT, overwrite release. Else, skip release if it already exists
+          skip_existing: ${{ ! contains(steps.chart-details.version, '-SNAPSHOT') }}
           pages_branch: gh-pages
           config: helm-releaser-config.yaml
         env:
